Switch to Suru cursor theme
ubuntu/communitheme-snap-helpers pull request #15
Opened 2018-07-04 17:26 UTC by galgalesh

This is the second part of https://github.com/ubuntu/communitheme-snap-helpers/pull/13

2018-07-04 17:31 UTC, didrocks commented
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-snap-helpers-pr15`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-snap-helpers-pr15` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

2018-07-04 17:34 UTC, didrocks commented
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-snap-helpers-pr15`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-snap-helpers-pr15` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

2018-07-09 11:25 UTC, didrocks requested changes
Thanks for proposing this! Check my comments, I think it's worth doing this, which is a bit better IMHO than restarting snapcraft inside snapcraft ;)

2018-07-09 11:25 UTC, didrocks commented on snap/snapcraft.yaml
> +    override-build: |
I would keep the normal `build` step, and rather do things in the `install` step. You can take some inspirations from https://github.com/snapcrafters/gtk-common-themes/blob/master/snap/snapcraft.yaml#L178

2018-07-09 11:56 UTC, galgalesh commented
Using the `install` step gives a deprecation warning which suggests this method: https://docs.snapcraft.io/deprecation-notices/dn9

I personally also prefer `override-build`  because it's more clear to me what is actually happening, less "magic".

2018-07-09 14:03 UTC, didrocks commented
Interesting… Ok, not sure I'm a really big fan of this, but ok, as it's in the doc :p

2018-07-09 14:03 UTC, didrocks approved these changes

2018-07-09 14:04 UTC, merged